/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.cifpaviles.dam.diact1_2;
import javax.swing.JFormattedTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author samuelmv
 */
public class Formulario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Formulario.class.getName());
    
    private static List<Alumno> listaAlumnos = new ArrayList<>();

    //Alumno [] array5Objetos = new Alumno[5];//array de 5 alumnos(tiene que ser estatico)
    /**
     * Creates new form Forumulario
     */
   public Formulario() {
    initComponents();
   }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNOMBRE = new javax.swing.JTextField();
        jTextFieldAPELLIDO = new javax.swing.JTextField();
        jTextFieldEMAIL = new javax.swing.JTextField();
        jTextFieldEDAD = new javax.swing.JTextField();
        jTextFieldTELF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        alumnoQueCrea = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("nombre");

        jLabel2.setText("apellido");

        jLabel3.setText("edad");

        jLabel4.setText("email");

        jLabel5.setText("telf");

        jTextFieldNOMBRE.setText("nombre");
        jTextFieldNOMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNOMBREActionPerformed(evt);
            }
        });

        jTextFieldAPELLIDO.setText("apellido");
        jTextFieldAPELLIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAPELLIDOActionPerformed(evt);
            }
        });

        jTextFieldEMAIL.setText("email");
        jTextFieldEMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEMAILActionPerformed(evt);
            }
        });

        jTextFieldEDAD.setText("edad");
        jTextFieldEDAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEDADActionPerformed(evt);
            }
        });

        jTextFieldTELF.setText("telf");
        jTextFieldTELF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTELFActionPerformed(evt);
            }
        });

        jButton1.setText("aniadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //jButton1ActionPerformed(evt);
            	 Alumno alumno = new Alumno(
            		        jTextFieldNOMBRE.getText(),
            		        jTextFieldAPELLIDO.getText(),
            		        jTextFieldEMAIL.getText(),
            		        Integer.parseInt(jTextFieldEDAD.getText()),
            		        Integer.parseInt(jTextFieldTELF.getText())
            	);
            	
            	 listaAlumnos.add(alumno);
            }
        });
        
        

        alumnoQueCrea.setText("ALUMNO QUE SE CREA");
        
        
        	table = new JTable();
        	table.setBackground(new Color(128, 255, 0));
        	
        	
        	

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(22)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel3)
        								.addComponent(jLabel5))
        							.addGap(18)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jTextFieldTELF, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jTextFieldEDAD, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jButton1)))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel1)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jTextFieldNOMBRE, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel2)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jTextFieldAPELLIDO, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel4)
        							.addGap(18)
        							.addComponent(jTextFieldEMAIL, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE))))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap(191, Short.MAX_VALUE)
        					.addComponent(alumnoQueCrea)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(table, GroupLayout.PREFERRED_SIZE, 261, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(15)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(table, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(jTextFieldNOMBRE, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        						.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        					.addGap(12)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel2)
        						.addComponent(jTextFieldAPELLIDO, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jTextFieldEMAIL, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3)
        				.addComponent(jTextFieldEDAD, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel5)
        				.addComponent(jTextFieldTELF, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jButton1)
        			.addGap(9)
        			.addComponent(alumnoQueCrea, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNOMBREActionPerformed
            //texto del nombre
    }//GEN-LAST:event_jTextFieldNOMBREActionPerformed

    private void jTextFieldAPELLIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAPELLIDOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAPELLIDOActionPerformed

    private void jTextFieldEMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEMAILActionPerformed

    private void jTextFieldEDADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEDADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEDADActionPerformed

    private void jTextFieldTELFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTELFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTELFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
            //Obtener los valores de los JTextField
            String nombre = jTextFieldNOMBRE.getText();
            String apellido = jTextFieldAPELLIDO.getText();
            String email = jTextFieldEMAIL.getText();
            int edad = Integer.parseInt(jTextFieldEDAD.getText());
            int telf = Integer.parseInt(jTextFieldTELF.getText());

            //Crear el objeto Alumno
            Alumno nuevoAlumno = new Alumno(nombre, apellido, email, edad, telf);

            //(Ejemplo) Mostrarlo por consola o guardarlo en un array
             alumnoQueCrea.setText("Alumno: " + nuevoAlumno.toString());

            //Principal.agregarAlumno(nuevoAlumno);

            //(Opcional) Mostrar confirmación
            javax.swing.JOptionPane.showMessageDialog(this, "Alumno añadido correctamente");

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Edad debe ser un número");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Formulario().setVisible(true));
    }

   
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alumnoQueCrea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldAPELLIDO;
    private javax.swing.JTextField jTextFieldEDAD;
    private javax.swing.JTextField jTextFieldEMAIL;
    private javax.swing.JTextField jTextFieldNOMBRE;
    private javax.swing.JTextField jTextFieldTELF;
    private JTable table;
}
